# Generated by Django 3.2.8 on 2021-11-10 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_order_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='frist_name',
            new_name='first_name',
        ),
    ]
