# Generated by Django 3.2.8 on 2021-11-17 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_rename_frist_name_order_first_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScienceBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('publisher', models.CharField(max_length=255, verbose_name='Издательство')),
                ('binding', models.CharField(max_length=255, verbose_name='Переплет')),
                ('size', models.CharField(max_length=255, verbose_name='Размер')),
                ('paper', models.CharField(max_length=255, verbose_name='Бумага')),
                ('ISBN', models.CharField(max_length=255, verbose_name='ISBN')),
                ('edition', models.PositiveIntegerField(default=0, verbose_name='Тираж')),
                ('language', models.CharField(max_length=255, verbose_name='Язык')),
                ('product_code', models.CharField(max_length=255, verbose_name='Код товара')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категория')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FictionBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('publisher', models.CharField(max_length=255, verbose_name='Издательство')),
                ('binding', models.CharField(max_length=255, verbose_name='Переплет')),
                ('size', models.CharField(max_length=255, verbose_name='Размер')),
                ('paper', models.CharField(max_length=255, verbose_name='Бумага')),
                ('ISBN', models.CharField(max_length=255, verbose_name='ISBN')),
                ('edition', models.PositiveIntegerField(default=0, verbose_name='Тираж')),
                ('language', models.CharField(max_length=255, verbose_name='Язык')),
                ('product_code', models.CharField(max_length=255, verbose_name='Код товара')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категория')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
