# Generated by Django 3.2.8 on 2021-11-17 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_fictionbook_sciencebook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smartphone',
            name='category',
        ),
        migrations.DeleteModel(
            name='Notebook',
        ),
        migrations.DeleteModel(
            name='Smartphone',
        ),
    ]
